# Array on Numpy

In [1]:
import numpy as np

In [2]:
np.array([a,b,c,d,e])

NameError: name 'a' is not defined

In [3]:
np.array([1,2,3,4,5,5])

array([1, 2, 3, 4, 5, 5])

 Arrays of all Zeros, ones, and random numbers\
 np.zeros([no. of row, no. of columns])\
 np.one([no. of row, no. of columns])\
 np.random.rand(no. of row, no. of columns)

In [4]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [5]:
np.zeros([5,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones([3,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
r = np.random.rand(4,4)
r

array([[0.74970017, 0.23254755, 0.8580452 , 0.08507335],
       [0.93516399, 0.16763734, 0.52301918, 0.37984987],
       [0.93639   , 0.57451042, 0.75244802, 0.01798847],
       [0.43562369, 0.89409341, 0.90448516, 0.55388081]])

### Indexing

In [10]:
r[0]

array([0.74970017, 0.23254755, 0.8580452 , 0.08507335])

In [11]:
np.array([r[1],r[2]])

array([[0.93516399, 0.16763734, 0.52301918, 0.37984987],
       [0.93639   , 0.57451042, 0.75244802, 0.01798847]])

In [12]:
r[2,2]

0.7524480201074321

In [13]:
r[:,1]

array([0.23254755, 0.16763734, 0.57451042, 0.89409341])

In [14]:
r[2,:]

array([0.93639   , 0.57451042, 0.75244802, 0.01798847])

### To print diagnol elements only

In [15]:
for i in range(4):
    for j in range(4):
        if i==j:
            print(r[i,j])

0.7497001703570672
0.16763734323356394
0.7524480201074321
0.5538808093782487


In [16]:
for i in range(4):
    for j in range(4):
        if i==j:
            print(np.array(r[i,j]))

0.7497001703570672
0.16763734323356394
0.7524480201074321
0.5538808093782487


In [17]:
np.diag(r)

array([0.74970017, 0.16763734, 0.75244802, 0.55388081])

In [27]:
 for i in range(4):
    for j in range(4):
        if i==j:
            np.array([print(r[i,j])])

0.7497001703570672
0.16763734323356394
0.7524480201074321
0.5538808093782487
